export const HEALTH_CHECK_CONFIG = {
  DATABASE_TIMEOUT_MS: process.env.HEALTH_CHECK_DB_TIMEOUT_MS || 2000,
  CACHE_TTL_MS: process.env.HEALTH_CHECK_CACHE_TTL_MS || 5000,
  RATE_LIMIT: {
    MAX_REQUESTS: process.env.HEALTH_CHECK_RATE_LIMIT_MAX || 10,
    WINDOW_MS: process.env.HEALTH_CHECK_RATE_LIMIT_WINDOW_MS || 60000
  }
};